version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Montowanie pliku bazy danych
      - ./static:/app/static          # Montowanie plików statycznych
    environment:
      DEBUG: "True"